### ISSUE TITLE
OIM 3640-01: Why we need an extra line of 'console.print' with nothing in the parenthesis?

### ISSUE THREAD

**Issue by msy011015** [OIM3640/oim3640#2]
https://github.com/OIM3640/oim3640/blob/9580dfad098b9860b22ee8568d2d638305950c39/session03/calc_sol_using_rich.py#L25

**Comment by lzblack** [comment]
Just to add an empty line to separate each question in the output.

**Comment by msy011015** [comment]
Thanks!
