### ISSUE TITLE
OIM3640-01: Questions

### ISSUE THREAD

**Issue by msy011015** [OIM3640/oim3640#3]
https://github.com/OIM3640/oim3640/blob/9580dfad098b9860b22ee8568d2d638305950c39/session03/calc_sol_using_rich.py#L44-L47
In line 44, it is ":04.1f“. But in the line 47, it is ":05.1%". ".1f" represents 1 digit after the decimal. What's the difference between 04 and 05? Thanks!

**Comment by lzblack** [comment]
The outputs of two `print` statements should look the same. The placeholder in Line 47 includes `%` in the output, so it would take one more space than the one in Line 44.

**Comment by msy011015** [comment]
Thanks!!!
